### ISSUE TITLE
To be Fixed

### ISSUE THREAD

**Issue by liondy** [liondy/CRM#4]
- [x]  Klien Delete tidak boleh dihapus data kliennya melainkan hanya di update saja statusnya jadi 0. 
- [x] Update tabel region menjadi punya `idRegion`
- [x] Investasi Delete tidak boleh dihapus data investasinya melainkan di jadikan 0 saja, tapi kalau gitu nanti untuk laporan MAX MIN nya pun harus di cek agar tidak menampilkan investasi 0 sebagai investasi minimal, juga tidak menampilkan investasi maksimal yang kliennya sudah tidak aktif lagi
- [ ] Cek seluruh SP yang ada hubungannya dengan Region (uda di list di bagian Readme.md)

**Comment by cristine27** [comment]
investasi done

**Comment by cristine27** [comment]
klien done

**Comment by liondy** [comment]
untuk bagian region baru diubah bagian insertnya saja

**Comment by liondy** [comment]
UPDATE:
1. untuk klienDelete di Laporannya harus diganti sedikit karena paramnya diganti --> @friskac 
2. updateReg harus dipikirkan kembali efektifitas penjalanan SP nya --> bersama (mungkin @denisestevani) kemudian tentunya update laporannya --> kyknya gausah
3. investasiUpdate sepertinya akan diubah paramnya jadi data-data klien (sama seperti klienDelete) --> @liondy kemudian tentunya update laporannya --> done
4. klienDelete harus menghapus hubungan juga (panggil SP hubunganDelete) --> @cristine27 --> X tidak usah

**Comment by liondy** [comment]
untuk cek semua SP yang berhubungan sama region karena kolomnya nambah te uda belum yah? gw lost
